namespace Koralytics.Application.DTOs.Analytics
{
    /// <summary>
    /// Response returned to the Angular frontend from the AI Player Search endpoint.
    /// </summary>
    public class AiSearchResponseDto
    {
        /// <summary>
        /// The human-readable answer generated by the AI agent.
        /// </summary>
        public string Answer { get; set; } = string.Empty;
    }
}
